version: '3'

services:
  rss-bot:
    build: .
    container_name: rss-discord-bot
    restart: always
    volumes:
      - rss_data:/data
      - ./src:/app/src  # srcディレクトリをマウント（開発時に便利）
    env_file:
      - .env

volumes:
  rss_data: